# Generated by Django 4.0.3 on 2022-06-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlist',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
