# Generated by Django 4.0.3 on 2022-06-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_productlist_unit_price_product_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='sold_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
