# Generated by Django 4.0.3 on 2022-06-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_productlist_sold_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlist',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
